export const githubResponse = [
  {
    // PR #1: Belongs to 'tenant1'
    pr: {
      url: 'https://api.github.com/repos/NASA-IMPACT/veda-data/pulls/1',
      id: 2242658313,
      node_id: 'PR_kwDOEu78RM6FrEAJ',
      html_url: 'https://github.com/NASA-IMPACT/veda-data/pull/1',
      diff_url: 'https://github.com/NASA-IMPACT/veda-data/pull/1.diff',
      patch_url: 'https://github.com/NASA-IMPACT/veda-data/pull/1.patch',
      issue_url: 'https://api.github.com/repos/NASA-IMPACT/veda-data/issues/1',
      number: 1,
      state: 'open',
      locked: false,
      title: 'Ingest Request for seeded ingest #1',
      user: {
        login: 'veda-test[bot]',
        id: 189034726,
        avatar_url: 'https://avatars.githubusercontent.com/u/1234',
        type: 'Bot',
        site_admin: false,
      },
      body: null,
      created_at: '2025-01-10T16:29:12Z',
      updated_at: '2025-01-10T16:29:12Z',
      closed_at: null,
      merged_at: null,
      head: {
        label: 'testuser:feat/seededigest1',
        ref: 'feat/seededingest1',
        sha: 'cd77775586e2d0369905cf0276a154f1f882f333',
        user: { login: 'testuser', id: 123456 },
        repo: { full_name: 'NASA-IMPACT/veda-data' },
      },
      base: { ref: 'main' },
      author_association: 'CONTRIBUTOR',
    },
    'local:tenant': 'tenant1',
  },
  {
    pr: {
      url: 'https://api.github.com/repos/NASA-IMPACT/veda-data/pulls/2',
      id: 2240904598,
      node_id: 'PR_kwDOEu78RM6FkX2W',
      html_url: 'https://github.com/NASA-IMPACT/veda-data/pull/2',
      diff_url: 'https://github.com/NASA-IMPACT/veda-data/pull/2.diff',
      patch_url: 'https://github.com/NASA-IMPACT/veda-data/pull/2.patch',
      issue_url: 'https://api.github.com/repos/NASA-IMPACT/veda-data/issues/2',
      number: 2,
      state: 'open',
      locked: false,
      title: 'Ingest Request for seeded Ingest #2',
      user: {
        login: 'veda-test[bot]',
        id: 189034726,
        avatar_url: 'https://avatars.githubusercontent.com/u/123456?v=4',
        type: 'Bot',
        site_admin: false,
      },
      body: null,
      created_at: '2025-01-09T23:15:59Z',
      updated_at: '2025-01-09T23:45:45Z',
      closed_at: null,
      merged_at: null,
      head: {
        label: 'testuser:feat/seededingest2',
        ref: 'feat/seededingest2',
        sha: '83e325b24fe5af99f42091609d2bc79655379d73',
        user: { login: 'testuser', id: 123456 },
        repo: { full_name: 'NASA-IMPACT/veda-data' },
      },
      base: { ref: 'main' },
      author_association: 'CONTRIBUTOR',
    },
    'local:tenant': 'tenant3',
  },
  {
    // PR #3: Public (no tenants specified)
    pr: {
      url: 'https://api.github.com/repos/NASA-IMPACT/veda-data/pulls/3',
      id: 2250000003,
      number: 3,
      state: 'open',
      locked: false,
      title: 'Public Landsat Ingest',
      user: {
        login: 'veda-test[bot]',
        id: 189034726,
        type: 'Bot',
        site_admin: false,
      },
      body: 'A public dataset for all users.',
      created_at: '2025-01-11T10:00:00Z',
      updated_at: '2025-01-11T10:00:00Z',
      closed_at: null,
      merged_at: null,
      head: {
        label: 'testuser:feat/public-landsat',
        ref: 'feat/public-landsat',
        sha: 'aaaabbbbccccddddeeeeffff1111222233334444',
        user: { login: 'testuser', id: 123456 },
        repo: { full_name: 'NASA-IMPACT/veda-data' },
      },
      base: { ref: 'main' },
      author_association: 'CONTRIBUTOR',
    },
    // No 'tenants' key makes this a public ingest
  },
  {
    pr: {
      url: 'https://api.github.com/repos/NASA-IMPACT/veda-data/pulls/4',
      id: 2250000004,
      number: 4,
      state: 'open',
      locked: false,
      title: 'Seeded Ingest #3 for tenant3',
      user: {
        login: 'veda-test[bot]',
        id: 189034726,
        type: 'Bot',
        site_admin: false,
      },
      body: 'A shared dataset for specific tenants.',
      created_at: '2025-01-12T11:30:00Z',
      updated_at: '2025-01-12T11:30:00Z',
      closed_at: null,
      merged_at: null,
      head: {
        label: 'testuser:feat/multi-tenant-sentinel',
        ref: 'feat/multi-tenant-sentinel',
        sha: '55556666777788889999aaaabbbbccccddddeeee',
        user: { login: 'testuser', id: 123456 },
        repo: { full_name: 'NASA-IMPACT/veda-data' },
      },
      base: { ref: 'main' },
      author_association: 'CONTRIBUTOR',
    },
    'local:tenant': 'tenant3',
  },
];
